# Generated by Django 5.1.15 on 2026-07-09 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_plugin_storeplugin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('full_name', models.CharField(max_length=200, verbose_name='نام')),
                ('phone', models.CharField(max_length=15, verbose_name='موبایل')),
                ('province', models.CharField(max_length=100, verbose_name='استان')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('postal_code', models.CharField(max_length=10, verbose_name='کد پستی')),
                ('address_line', models.TextField(verbose_name='آدرس')),
                ('building_no', models.CharField(blank=True, max_length=20, verbose_name='پلاک')),
                ('unit', models.CharField(blank=True, max_length=20, verbose_name='واحد')),
                ('label', models.CharField(blank=True, max_length=50, verbose_name='برچسب')),
                ('is_default', models.BooleanField(default=False, verbose_name='پیش\u200cفرض')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='tenants.store', verbose_name='فروشگاه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'آدرس مشتری',
                'verbose_name_plural': 'آدرس\u200cهای مشتری',
                'ordering': ['-is_default', '-updated_at'],
            },
        ),
    ]
