# Generated by Django 5.1.15 on 2026-07-09 21:29

import django.core.validators
import django.db.models.deletion
import payments.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_plugin_storeplugin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('gateway', models.CharField(choices=[('zarinpal', 'زرین\u200cپال'), ('idpay', 'آیدی\u200cپی'), ('mellat', 'ملت'), ('pasargad', 'پاسارگاد')], max_length=20, verbose_name='درگاه')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('redirected', 'انتقال به درگاه'), ('paid', 'پرداخت شده'), ('failed', 'ناموفق'), ('refunded', 'بازگشت وجه'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('tracking_code', models.CharField(default=payments.models.generate_tracking_code, max_length=32, unique=True, verbose_name='کد پیگیری')),
                ('authority', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Authority')),
                ('ref_id', models.CharField(blank=True, max_length=100, verbose_name='Ref ID')),
                ('payment_url', models.URLField(blank=True, verbose_name='آدرس پرداخت')),
                ('callback_url', models.CharField(blank=True, max_length=500, verbose_name='Callback')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='متادیتا')),
                ('verify_data', models.JSONField(blank=True, default=dict, verbose_name='پاسخ تایید')),
                ('error_message', models.TextField(blank=True, verbose_name='خطا')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پرداخت')),
                ('refunded_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ بازگشت')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tenants.store', verbose_name='فروشگاه')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تراکنش پرداخت',
                'verbose_name_plural': 'تراکنش\u200cهای پرداخت',
                'ordering': ['-created_at'],
            },
        ),
    ]
