# Generated by Django 5.1.15 on 2026-07-10 08:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('tenants', '0002_plugin_storeplugin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['store', 'status'], name='payments_pa_store_i_a80a31_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['store', 'created_at'], name='payments_pa_store_i_962e7a_idx'),
        ),
    ]
