# Generated by Django 5.1.15 on 2026-08-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_add_performance_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='gateway',
            field=models.CharField(choices=[('zarinpal', 'زرین\u200cپال'), ('idpay', 'آیدی\u200cپی'), ('mellat', 'ملت'), ('pasargad', 'پاسارگاد'), ('sina', 'سینا')], max_length=20, verbose_name='درگاه'),
        ),
    ]
