[pytest]
DJANGO_SETTINGS_MODULE = config.settings.test
python_files = tests.py test_*.py *_tests.py
addopts = -v --tb=short
testpaths = accounts addresses blog carts cms comments core dashboard digital files notifications orders payments plugins products reports shipping subscriptions taxes tenants wishlists tests
