# Generated by Django 5.1.15 on 2026-07-10 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_plugin_storeplugin'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('scope', models.CharField(choices=[('store', 'Store'), ('platform', 'Platform')], default='store', max_length=20, verbose_name='محدوده')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='مسیر فایل')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='حجم فایل')),
                ('include_media', models.BooleanField(default=True, verbose_name='شامل رسانه')),
                ('record_count', models.PositiveIntegerField(default=0, verbose_name='تعداد رکورد')),
                ('checksum', models.CharField(blank=True, max_length=64, verbose_name='Checksum')),
                ('error_message', models.TextField(blank=True, verbose_name='خطا')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان اتمام')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backup_jobs', to='tenants.store', verbose_name='فروشگاه')),
            ],
            options={
                'verbose_name': 'بکاپ',
                'verbose_name_plural': 'بکاپ\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
