# Generated by Django 5.1.15 on 2026-07-10 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_backup_job'),
        ('tenants', '0002_plugin_storeplugin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('register', 'Register'), ('otp_send', 'OTP Send'), ('otp_failed', 'OTP Failed'), ('token_refresh', 'Token Refresh'), ('two_fa_verify', '2FA Verify'), ('two_fa_enable', '2FA Enable'), ('two_fa_disable', '2FA Disable'), ('permission_denied', 'Permission Denied'), ('device_revoke', 'Device Revoke'), ('rate_limited', 'Rate Limited')], max_length=50, verbose_name='عملیات')),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('blocked', 'Blocked')], default='success', max_length=20, verbose_name='نتیجه')),
                ('resource_type', models.CharField(blank=True, max_length=100, verbose_name='نوع منبع')),
                ('resource_id', models.CharField(blank=True, max_length=100, verbose_name='شناسه منبع')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='متادیتا')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='tenants.store', verbose_name='فروشگاه')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'لاگ امنیتی',
                'verbose_name_plural': 'لاگ\u200cهای امنیتی',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['store', 'action', '-created_at'], name='core_auditl_store_i_756151_idx'), models.Index(fields=['user', '-created_at'], name='core_auditl_user_id_969660_idx')],
            },
        ),
    ]
