# Generated by Django 5.1.15 on 2026-07-09 21:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('tenants', '0002_plugin_storeplugin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('code', models.CharField(max_length=50, verbose_name='کد')),
                ('discount_type', models.CharField(choices=[('percentage', 'درصدی'), ('fixed', 'مبلغ ثابت')], default='percentage', max_length=20, verbose_name='نوع تخفیف')),
                ('value', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مقدار')),
                ('min_order_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='حداقل سفارش')),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True, verbose_name='حداکثر استفاده')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='تعداد استفاده')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='شروع اعتبار')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='پایان اعتبار')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('first_purchase_only', models.BooleanField(default=False, verbose_name='فقط اولین خرید')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='tenants.store', verbose_name='فروشگاه')),
            ],
            options={
                'verbose_name': 'کوپن',
                'verbose_name_plural': 'کوپن\u200cها',
                'ordering': ['-created_at'],
                'unique_together': {('store', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='کلید نشست')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='tenants.store', verbose_name='فروشگاه')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='carts.coupon', verbose_name='کوپن')),
            ],
            options={
                'verbose_name': 'سبد خرید',
                'verbose_name_plural': 'سبدهای خرید',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت واحد')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='carts.cart', verbose_name='سبد')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='products.product', verbose_name='محصول')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='products.productvariant', verbose_name='تنوع')),
            ],
            options={
                'verbose_name': 'آیتم سبد',
                'verbose_name_plural': 'آیتم\u200cهای سبد',
                'unique_together': {('cart', 'product', 'variant')},
            },
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('store', 'user'), name='unique_cart_per_user_store'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True), models.Q(('session_key', ''), _negated=True)), fields=('store', 'session_key'), name='unique_cart_per_session_store'),
        ),
    ]
