# Generated by Django 5.1.15 on 2026-07-09 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_plugin_storeplugin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='عنوان SEO')),
                ('meta_description', models.CharField(blank=True, max_length=500, verbose_name='توضیح SEO')),
                ('meta_keywords', models.CharField(blank=True, max_length=500, verbose_name='کلمات کلیدی')),
                ('og_image', models.URLField(blank=True, verbose_name='تصویر Open Graph')),
                ('canonical_url', models.URLField(blank=True, verbose_name='URL کانونیکال')),
                ('robots', models.CharField(default='index,follow', max_length=100, verbose_name='Robots')),
                ('head_scripts', models.TextField(blank=True, verbose_name='اسکریپت Head')),
                ('footer_scripts', models.TextField(blank=True, verbose_name='اسکریپت Footer')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='زیرعنوان')),
                ('image', models.URLField(blank=True, verbose_name='تصویر')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='لینک')),
                ('position', models.CharField(choices=[('home_top', 'بالای صفحه خانه'), ('home_middle', 'وسط صفحه خانه'), ('category_top', 'بالای دسته\u200cبندی'), ('sidebar', 'سایدبار')], max_length=30, verbose_name='موقعیت')),
                ('sort_order', models.IntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='شروع')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='پایان')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='tenants.store', verbose_name='فروشگاه')),
            ],
            options={
                'verbose_name': 'بنر',
                'verbose_name_plural': 'بنرها',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LayoutSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('header_html', models.TextField(blank=True, verbose_name='HTML هدر')),
                ('footer_html', models.TextField(blank=True, verbose_name='HTML فوتر')),
                ('use_custom_header', models.BooleanField(default=False, verbose_name='هدر سفارشی')),
                ('use_custom_footer', models.BooleanField(default=False, verbose_name='فوتر سفارشی')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='layout_settings', to='tenants.store', verbose_name='فروشگاه')),
            ],
            options={
                'verbose_name': 'تنظیمات چیدمان',
                'verbose_name_plural': 'تنظیمات چیدمان',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('location', models.CharField(choices=[('header', 'هدر'), ('footer', 'فوتر'), ('sidebar', 'سایدبار')], max_length=20, verbose_name='مکان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='tenants.store', verbose_name='فروشگاه')),
            ],
            options={
                'verbose_name': 'منو',
                'verbose_name_plural': 'منوها',
                'ordering': ['location'],
                'unique_together': {('store', 'location')},
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='عنوان SEO')),
                ('meta_description', models.CharField(blank=True, max_length=500, verbose_name='توضیح SEO')),
                ('meta_keywords', models.CharField(blank=True, max_length=500, verbose_name='کلمات کلیدی')),
                ('og_image', models.URLField(blank=True, verbose_name='تصویر Open Graph')),
                ('canonical_url', models.URLField(blank=True, verbose_name='URL کانونیکال')),
                ('robots', models.CharField(default='index,follow', max_length=100, verbose_name='Robots')),
                ('head_scripts', models.TextField(blank=True, verbose_name='اسکریپت Head')),
                ('footer_scripts', models.TextField(blank=True, verbose_name='اسکریپت Footer')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=200, verbose_name='شناسه')),
                ('content', models.TextField(blank=True, verbose_name='محتوا')),
                ('template', models.CharField(blank=True, max_length=100, verbose_name='قالب')),
                ('is_published', models.BooleanField(default=True, verbose_name='منتشر شده')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('sort_order', models.IntegerField(default=0, verbose_name='ترتیب')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='tenants.store', verbose_name='فروشگاه')),
            ],
            options={
                'verbose_name': 'صفحه',
                'verbose_name_plural': 'صفحات',
                'ordering': ['sort_order', 'title'],
                'unique_together': {('store', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('label', models.CharField(max_length=100, verbose_name='برچسب')),
                ('url', models.CharField(blank=True, max_length=500, verbose_name='لینک')),
                ('sort_order', models.IntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('open_new_tab', models.BooleanField(default=False, verbose_name='تب جدید')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cms.menu', verbose_name='منو')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cms.menuitem', verbose_name='والد')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='cms.page', verbose_name='صفحه')),
            ],
            options={
                'verbose_name': 'آیتم منو',
                'verbose_name_plural': 'آیتم\u200cهای منو',
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('slug', models.SlugField(max_length=100, verbose_name='شناسه')),
                ('autoplay', models.BooleanField(default=True, verbose_name='پخش خودکار')),
                ('interval', models.PositiveIntegerField(default=5000, verbose_name='فاصله (ms)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sliders', to='tenants.store', verbose_name='فروشگاه')),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'اسلایدرها',
                'ordering': ['name'],
                'unique_together': {('store', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='عنوان')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='زیرعنوان')),
                ('image', models.URLField(verbose_name='تصویر')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='لینک')),
                ('sort_order', models.IntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='cms.slider', verbose_name='اسلایدر')),
            ],
            options={
                'verbose_name': 'اسلاید',
                'verbose_name_plural': 'اسلایدها',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('slug', models.SlugField(max_length=100, verbose_name='شناسه')),
                ('widget_type', models.CharField(choices=[('html', 'HTML'), ('text', 'متن'), ('image', 'تصویر'), ('product_list', 'لیست محصولات'), ('banner', 'بنر')], default='html', max_length=30, verbose_name='نوع')),
                ('content', models.JSONField(default=dict, verbose_name='محتوا')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='tenants.store', verbose_name='فروشگاه')),
            ],
            options={
                'verbose_name': 'ویجت',
                'verbose_name_plural': 'ویجت\u200cها',
                'ordering': ['name'],
                'unique_together': {('store', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('block_type', models.CharField(choices=[('hero', 'هیرو'), ('text', 'متن'), ('image', 'تصویر'), ('html', 'HTML'), ('widget', 'ویجت')], default='text', max_length=20, verbose_name='نوع')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='عنوان')),
                ('content', models.JSONField(default=dict, verbose_name='محتوا')),
                ('sort_order', models.IntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='cms.page', verbose_name='صفحه')),
                ('widget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocks', to='cms.widget', verbose_name='ویجت')),
            ],
            options={
                'verbose_name': 'بلوک محتوا',
                'verbose_name_plural': 'بلوک\u200cهای محتوا',
                'ordering': ['sort_order'],
            },
        ),
    ]
