# Generated by Django 5.1.15 on 2026-07-18 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
        ('tenants', '0002_plugin_storeplugin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shortcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('name', models.SlugField(verbose_name='نام shortcode')),
                ('label', models.CharField(max_length=100, verbose_name='برچسب')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='توضیحات')),
                ('html_template', models.TextField(help_text='از {{content}} و {{نام_ویژگی}} استفاده کنید', verbose_name='قالب HTML')),
                ('is_self_closing', models.BooleanField(default=False, verbose_name='بدون تگ پایانی')),
                ('example', models.TextField(blank=True, verbose_name='مثال')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortcodes', to='tenants.store', verbose_name='فروشگاه')),
            ],
            options={
                'verbose_name': 'شورت\u200cکد',
                'verbose_name_plural': 'شورت\u200cکدها',
                'ordering': ['name'],
                'unique_together': {('store', 'name')},
            },
        ),
    ]
