# Generated by Django 5.1.15 on 2026-07-09 20:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('name', models.CharField(max_length=200, verbose_name='نام فروشگاه')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='شناسه')),
                ('store_type', models.CharField(choices=[('physical', 'کالای فیزیکی + پست'), ('digital_download', 'کالای دیجیتال + دانلود'), ('subscription', 'کالای دیجیتال + اشتراک'), ('booking', 'رزرو + خرید خدمت'), ('appointment', 'رزرو + نوبت'), ('rental', 'اجاره'), ('print_on_demand', 'کالای سفارشی')], default='physical', max_length=30, verbose_name='نوع فروشگاه')),
                ('currency', models.CharField(default='IRR', max_length=10, verbose_name='ارز')),
                ('timezone', models.CharField(default='Asia/Tehran', max_length=50, verbose_name='منطقه زمانی')),
                ('language', models.CharField(default='fa', max_length=10, verbose_name='زبان')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیرفعال'), ('suspended', 'معلق')], default='active', max_length=20, verbose_name='وضعیت')),
                ('tax_enabled', models.BooleanField(default=False, verbose_name='مالیات فعال')),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد مالیات')),
            ],
            options={
                'verbose_name': 'فروشگاه',
                'verbose_name_plural': 'فروشگاه\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='شناسه')),
                ('directory', models.CharField(help_text='نام پوشه تم در themes/ (مثلاً modern)', max_length=200, verbose_name='پوشه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_default', models.BooleanField(default=False, verbose_name='پیش\u200cفرض')),
            ],
            options={
                'verbose_name': 'تم',
                'verbose_name_plural': 'تم\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('domain', models.CharField(help_text='مثلاً shop1.com یا shop.example.com', max_length=255, unique=True, verbose_name='دامنه')),
                ('is_primary', models.BooleanField(default=False, verbose_name='دامنه اصلی')),
                ('ssl_enabled', models.BooleanField(default=True, verbose_name='SSL فعال')),
                ('redirect_to_primary', models.BooleanField(default=False, help_text='در صورت فعال بودن به دامنه اصلی ریدایرکت شود', verbose_name='ریدایرکت به دامنه اصلی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.store', verbose_name='فروشگاه')),
            ],
            options={
                'verbose_name': 'دامنه',
                'verbose_name_plural': 'دامنه\u200cها',
                'ordering': ['-is_primary', 'domain'],
            },
        ),
        migrations.AddField(
            model_name='store',
            name='default_theme',
            field=models.ForeignKey(blank=True, help_text='تم پیش\u200cفرض در صورت نبود تم اختصاصی', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_stores', to='tenants.theme', verbose_name='تم پیش\u200cفرض'),
        ),
        migrations.AddField(
            model_name='store',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores', to='tenants.theme', verbose_name='تم'),
        ),
        migrations.CreateModel(
            name='StoreSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('group', models.CharField(default='general', help_text='مثلاً payment, shipping, theme', max_length=100, verbose_name='گروه')),
                ('key', models.CharField(max_length=200, verbose_name='کلید')),
                ('value', models.JSONField(default=dict, verbose_name='مقدار')),
                ('value_type', models.CharField(choices=[('string', 'متن'), ('integer', 'عدد صحیح'), ('float', 'عدد اعشاری'), ('boolean', 'بولین'), ('json', 'JSON')], default='json', max_length=20, verbose_name='نوع مقدار')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='توضیحات')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='tenants.store', verbose_name='فروشگاه')),
            ],
            options={
                'verbose_name': 'تنظیمات فروشگاه',
                'verbose_name_plural': 'تنظیمات فروشگاه\u200cها',
                'ordering': ['group', 'key'],
                'unique_together': {('store', 'group', 'key')},
            },
        ),
    ]
