# Generated by Django 5.1.15 on 2026-07-09 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('codename', models.SlugField(unique=True, verbose_name='شناسه')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('compatible_store_types', models.JSONField(blank=True, default=list, help_text='لیست خالی = سازگار با همه انواع فروشگاه', verbose_name='انواع فروشگاه سازگار')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_system', models.BooleanField(default=True, verbose_name='سیستمی')),
            ],
            options={
                'verbose_name': 'افزونه',
                'verbose_name_plural': 'افزونه\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StorePlugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='فعال')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='تنظیمات')),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_plugins', to='tenants.plugin', verbose_name='افزونه')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plugins', to='tenants.store', verbose_name='فروشگاه')),
            ],
            options={
                'verbose_name': 'افزونه فروشگاه',
                'verbose_name_plural': 'افزونه\u200cهای فروشگاه',
                'ordering': ['plugin__name'],
                'unique_together': {('store', 'plugin')},
            },
        ),
    ]
