# Generated by Django 5.1.15 on 2026-08-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_plugin_storeplugin'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='origin_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='عرض جغرافیایی مبدا'),
        ),
        migrations.AddField(
            model_name='store',
            name='origin_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='طول جغرافیایی مبدا'),
        ),
        migrations.AlterField(
            model_name='storesetting',
            name='value',
            field=models.JSONField(blank=True, default=dict, verbose_name='مقدار'),
        ),
    ]
