# Generated by Django 5.1.15 on 2026-07-09 21:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('tenants', '0002_plugin_storeplugin'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('rate_percent', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد مالیات')),
                ('scope', models.CharField(choices=[('all', 'همه محصولات'), ('category', 'دسته\u200cبندی'), ('product', 'محصول')], default='all', max_length=20, verbose_name='محدوده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('priority', models.IntegerField(default=0, verbose_name='اولویت')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_rules', to='products.category', verbose_name='دسته\u200cبندی')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_rules', to='products.product', verbose_name='محصول')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_rules', to='tenants.store', verbose_name='فروشگاه')),
            ],
            options={
                'verbose_name': 'قانون مالیات',
                'verbose_name_plural': 'قوانین مالیات',
                'ordering': ['-priority', 'name'],
            },
        ),
    ]
