# Generated by Django 5.1.15 on 2026-07-09 22:19

import digital.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
        ('orders', '0002_order_gift_card_code'),
        ('products', '0002_alter_product_product_type'),
        ('tenants', '0002_plugin_storeplugin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('product_id', models.IntegerField(verbose_name='شناسه محصول')),
                ('token', models.CharField(default=digital.models.generate_download_token, max_length=64, unique=True, verbose_name='توکن')),
                ('max_downloads', models.PositiveIntegerField(default=5, verbose_name='حداکثر دانلود')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='تعداد دانلود')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('expired', 'منقضی'), ('exhausted', 'اتمام دانلود'), ('revoked', 'لغو شده')], default='active', max_length=20, verbose_name='وضعیت')),
                ('last_download_at', models.DateTimeField(blank=True, null=True, verbose_name='آخرین دانلود')),
                ('media_file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='download_licenses', to='files.mediafile', verbose_name='فایل')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_licenses', to='orders.order', verbose_name='سفارش')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_licenses', to='orders.orderitem', verbose_name='آیتم سفارش')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_licenses', to='tenants.store', verbose_name='فروشگاه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_licenses', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'مجوز دانلود',
                'verbose_name_plural': 'مجوزهای دانلود',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['store', 'user'], name='digital_dow_store_i_0df5f2_idx'), models.Index(fields=['token'], name='digital_dow_token_3fa477_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductDigitalAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='عنوان')),
                ('sort_order', models.IntegerField(default=0, verbose_name='ترتیب')),
                ('max_downloads', models.PositiveIntegerField(blank=True, null=True, verbose_name='حداکثر دانلود')),
                ('expire_hours', models.PositiveIntegerField(blank=True, null=True, verbose_name='انقضا (ساعت)')),
                ('media_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_assets', to='files.mediafile', verbose_name='فایل')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_assets', to='products.product', verbose_name='محصول')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_assets', to='tenants.store', verbose_name='فروشگاه')),
            ],
            options={
                'verbose_name': 'فایل دیجیتال محصول',
                'verbose_name_plural': 'فایل\u200cهای دیجیتال محصول',
                'ordering': ['sort_order', 'id'],
                'unique_together': {('product', 'media_file')},
            },
        ),
    ]
