# Generated by Django 5.1.15 on 2026-07-09 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('codename', models.CharField(max_length=100, unique=True, verbose_name='شناسه')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('group', models.CharField(default='general', max_length=100, verbose_name='گروه')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'دسترسی',
                'verbose_name_plural': 'دسترسی\u200cها',
                'ordering': ['group', 'codename'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('phone', models.CharField(max_length=15, unique=True, verbose_name='موبایل')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='نام خانوادگی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_staff', models.BooleanField(default=False, verbose_name='دسترسی ادمین')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='سوپرادمین')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='آخرین IP')),
                ('phone_verified', models.BooleanField(default=False, verbose_name='موبایل تایید شده')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('codename', models.CharField(max_length=50, unique=True, verbose_name='شناسه')),
                ('scope', models.CharField(choices=[('platform', 'پلتفرم'), ('store', 'فروشگاه')], default='store', max_length=20, verbose_name='محدوده')),
                ('is_system', models.BooleanField(default=False, help_text='نقش\u200cهای سیستمی قابل حذف نیستند', verbose_name='سیستمی')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='توضیحات')),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='accounts.permission', verbose_name='دسترسی\u200cها')),
            ],
            options={
                'verbose_name': 'نقش',
                'verbose_name_plural': 'نقش\u200cها',
                'ordering': ['scope', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('phone', models.CharField(max_length=15, verbose_name='موبایل')),
                ('code', models.CharField(max_length=6, verbose_name='کد')),
                ('purpose', models.CharField(choices=[('login', 'ورود'), ('register', 'ثبت\u200cنام')], max_length=20, verbose_name='هدف')),
                ('is_used', models.BooleanField(default=False, verbose_name='استفاده شده')),
                ('expires_at', models.DateTimeField(verbose_name='انقضا')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='تلاش\u200cها')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to='tenants.store', verbose_name='فروشگاه')),
            ],
            options={
                'verbose_name': 'کد OTP',
                'verbose_name_plural': 'کدهای OTP',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone', 'purpose', 'is_used'], name='accounts_ot_phone_98e2f1_idx')],
            },
        ),
        migrations.CreateModel(
            name='StoreMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیرفعال'), ('suspended', 'معلق')], default='active', max_length=20, verbose_name='وضعیت')),
                ('is_primary', models.BooleanField(default=False, help_text='ادمین اصلی فروشگاه', verbose_name='اصلی')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='accounts.role', verbose_name='نقش')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenants.store', verbose_name='فروشگاه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'عضویت فروشگاه',
                'verbose_name_plural': 'عضویت\u200cهای فروشگاه',
                'ordering': ['-is_primary', '-created_at'],
                'unique_together': {('user', 'store')},
            },
        ),
    ]
