# Generated by Django 5.1.15 on 2026-07-10 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_2fa_enabled', models.BooleanField(default=False, verbose_name='2FA فعال')),
                ('totp_secret', models.CharField(blank=True, max_length=64, verbose_name='TOTP Secret')),
                ('backup_codes', models.JSONField(blank=True, default=list, verbose_name='کدهای پشتیبان')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_settings', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تنظیمات امنیتی',
                'verbose_name_plural': 'تنظیمات امنیتی',
            },
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('device_key', models.CharField(max_length=64, verbose_name='کلید دستگاه')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='نام')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='آخرین بازدید')),
                ('is_trusted', models.BooleanField(default=False, verbose_name='مورد اعتماد')),
                ('is_revoked', models.BooleanField(default=False, verbose_name='لغو شده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'دستگاه کاربر',
                'verbose_name_plural': 'دستگاه\u200cهای کاربر',
                'ordering': ['-last_seen'],
                'unique_together': {('user', 'device_key')},
            },
        ),
    ]
