# Generated by Django 5.1.15 on 2026-07-09 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_plugin_storeplugin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('slug', models.SlugField(max_length=200, verbose_name='شناسه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_categories', to='tenants.store', verbose_name='فروشگاه')),
            ],
            options={
                'verbose_name': 'دسته وبلاگ',
                'verbose_name_plural': 'دسته\u200cهای وبلاگ',
                'ordering': ['name'],
                'unique_together': {('store', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='عنوان SEO')),
                ('meta_description', models.CharField(blank=True, max_length=500, verbose_name='توضیح SEO')),
                ('meta_keywords', models.CharField(blank=True, max_length=500, verbose_name='کلمات کلیدی')),
                ('og_image', models.URLField(blank=True, verbose_name='تصویر Open Graph')),
                ('canonical_url', models.URLField(blank=True, verbose_name='URL کانونیکال')),
                ('robots', models.CharField(default='index,follow', max_length=100, verbose_name='Robots')),
                ('head_scripts', models.TextField(blank=True, verbose_name='اسکریپت Head')),
                ('footer_scripts', models.TextField(blank=True, verbose_name='اسکریپت Footer')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=300, verbose_name='شناسه')),
                ('excerpt', models.TextField(blank=True, verbose_name='خلاصه')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('featured_image', models.URLField(blank=True, verbose_name='تصویر شاخص')),
                ('is_published', models.BooleanField(default=False, verbose_name='منتشر شده')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.blogcategory', verbose_name='دسته')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='tenants.store', verbose_name='فروشگاه')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('body', models.TextField(verbose_name='متن')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.blogcomment', verbose_name='پاسخ به')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_comments', to='tenants.store', verbose_name='فروشگاه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blogpost', verbose_name='مقاله')),
            ],
            options={
                'verbose_name': 'نظر وبلاگ',
                'verbose_name_plural': 'نظرات وبلاگ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('slug', models.SlugField(max_length=100, verbose_name='شناسه')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_tags', to='tenants.store', verbose_name='فروشگاه')),
            ],
            options={
                'verbose_name': 'برچسب وبلاگ',
                'verbose_name_plural': 'برچسب\u200cهای وبلاگ',
                'ordering': ['name'],
                'unique_together': {('store', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='blog.blogtag', verbose_name='برچسب\u200cها'),
        ),
        migrations.AlterUniqueTogether(
            name='blogpost',
            unique_together={('store', 'slug')},
        ),
    ]
