# Generated by Django 5.1.15 on 2026-07-09 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_order_gift_card_code'),
        ('products', '0003_alter_product_product_type'),
        ('tenants', '0002_plugin_storeplugin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('interval', models.CharField(choices=[('weekly', 'هفتگی'), ('monthly', 'ماهانه'), ('yearly', 'سالانه')], default='monthly', max_length=20, verbose_name='دوره')),
                ('interval_count', models.PositiveIntegerField(default=1, verbose_name='تعداد دوره')),
                ('trial_days', models.PositiveIntegerField(default=0, verbose_name='روز آزمایشی')),
                ('grace_period_days', models.PositiveIntegerField(default=3, verbose_name='مهلت تمدید')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_plan', to='products.product', verbose_name='محصول')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_plans', to='tenants.store', verbose_name='فروشگاه')),
            ],
            options={
                'verbose_name': 'پلن اشتراک',
                'verbose_name_plural': 'پلن\u200cهای اشتراک',
            },
        ),
        migrations.CreateModel(
            name='CustomerSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('status', models.CharField(choices=[('trialing', 'دوره آزمایشی'), ('active', 'فعال'), ('past_due', 'معوق'), ('canceled', 'لغو شده'), ('expired', 'منقضی')], default='active', max_length=20, verbose_name='وضعیت')),
                ('interval', models.CharField(choices=[('weekly', 'هفتگی'), ('monthly', 'ماهانه'), ('yearly', 'سالانه')], max_length=20, verbose_name='دوره')),
                ('interval_count', models.PositiveIntegerField(default=1, verbose_name='تعداد دوره')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='قیمت')),
                ('auto_renew', models.BooleanField(default=True, verbose_name='تمدید خودکار')),
                ('started_at', models.DateTimeField(verbose_name='شروع')),
                ('current_period_start', models.DateTimeField(verbose_name='شروع دوره جاری')),
                ('current_period_end', models.DateTimeField(verbose_name='پایان دوره جاری')),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='پایان آزمایشی')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان لغو')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='انقضا نهایی')),
                ('renewal_count', models.PositiveIntegerField(default=0, verbose_name='تعداد تمدید')),
                ('initial_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='orders.order', verbose_name='سفارش اولیه')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_subscriptions', to='products.product', verbose_name='محصول')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='tenants.store', verbose_name='فروشگاه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='subscriptions.subscriptionplan', verbose_name='پلن')),
            ],
            options={
                'verbose_name': 'اشتراک مشتری',
                'verbose_name_plural': 'اشتراک\u200cهای مشتری',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('period_start', models.DateTimeField(verbose_name='شروع دوره')),
                ('period_end', models.DateTimeField(verbose_name='پایان دوره')),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='مبلغ')),
                ('status', models.CharField(choices=[('success', 'موفق'), ('failed', 'ناموفق'), ('pending', 'در انتظار')], default='success', max_length=20, verbose_name='وضعیت')),
                ('payment_ref', models.CharField(blank=True, max_length=100, verbose_name='مرجع پرداخت')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='یادداشت')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='subscriptions.customersubscription', verbose_name='اشتراک')),
            ],
            options={
                'verbose_name': 'تمدید اشتراک',
                'verbose_name_plural': 'تمدیدهای اشتراک',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customersubscription',
            index=models.Index(fields=['store', 'user'], name='subscriptio_store_i_ea771c_idx'),
        ),
        migrations.AddIndex(
            model_name='customersubscription',
            index=models.Index(fields=['status', 'current_period_end'], name='subscriptio_status_a846a9_idx'),
        ),
    ]
