# Generated by Django 5.1.15 on 2026-07-09 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_plugin_storeplugin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('file_type', models.CharField(choices=[('image', 'تصویر'), ('video', 'ویدیو'), ('document', 'سند'), ('other', 'سایر')], default='other', max_length=20, verbose_name='نوع')),
                ('original_name', models.CharField(max_length=255, verbose_name='نام اصلی')),
                ('storage_path', models.CharField(max_length=500, verbose_name='مسیر ذخیره')),
                ('storage_driver', models.CharField(choices=[('local', 'Local'), ('s3', 'Amazon S3'), ('minio', 'MinIO'), ('r2', 'Cloudflare R2')], default='local', max_length=20, verbose_name='درایور')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME')),
                ('size_bytes', models.PositiveBigIntegerField(default=0, verbose_name='حجم')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='عرض')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='ارتفاع')),
                ('url', models.URLField(max_length=500, verbose_name='آدرس')),
                ('folder', models.CharField(blank=True, max_length=200, verbose_name='پوشه')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='عنوان')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='متن جایگزین')),
                ('is_public', models.BooleanField(default=True, verbose_name='عمومی')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='tenants.store', verbose_name='فروشگاه')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL, verbose_name='آپلودکننده')),
            ],
            options={
                'verbose_name': 'فایل',
                'verbose_name_plural': 'فایل\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileThumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('variant', models.CharField(choices=[('thumb', 'Thumbnail'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=20, verbose_name='اندازه')),
                ('storage_path', models.CharField(max_length=500, verbose_name='مسیر ذخیره')),
                ('url', models.URLField(max_length=500, verbose_name='آدرس')),
                ('width', models.PositiveIntegerField(default=0, verbose_name='عرض')),
                ('height', models.PositiveIntegerField(default=0, verbose_name='ارتفاع')),
                ('size_bytes', models.PositiveBigIntegerField(default=0, verbose_name='حجم')),
                ('media_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to='files.mediafile', verbose_name='فایل')),
            ],
            options={
                'verbose_name': 'Thumbnail',
                'verbose_name_plural': 'Thumbnailها',
                'ordering': ['variant'],
            },
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['store', 'file_type'], name='files_media_store_i_18bbab_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['store', 'folder'], name='files_media_store_i_30a92f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='filethumbnail',
            unique_together={('media_file', 'variant')},
        ),
    ]
