# Generated by Django 5.1.15 on 2026-07-09 21:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_plugin_storeplugin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('slug', models.SlugField(max_length=200, verbose_name='شناسه')),
                ('provider', models.CharField(choices=[('post', 'پست'), ('tipax', 'تیپاکس'), ('peyk', 'پیک'), ('free', 'ارسال رایگان'), ('api', 'API خارجی')], max_length=20, verbose_name='ارائه\u200cدهنده')),
                ('calculation_mode', models.CharField(choices=[('fixed', 'ثابت'), ('distance', 'مسافت'), ('weight', 'وزن'), ('distance_weight', 'مسافت + وزن'), ('api', 'API')], max_length=20, verbose_name='نوع محاسبه')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='تنظیمات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('sort_order', models.IntegerField(default=0, verbose_name='ترتیب')),
                ('min_order_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='حداقل سفارش')),
                ('free_shipping_threshold', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='آستانه ارسال رایگان')),
                ('estimated_days', models.PositiveIntegerField(default=3, verbose_name='زمان تحویل (روز)')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_methods', to='tenants.store', verbose_name='فروشگاه')),
            ],
            options={
                'verbose_name': 'روش ارسال',
                'verbose_name_plural': 'روش\u200cهای ارسال',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ShippingPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('from_city', models.CharField(blank=True, max_length=100, verbose_name='شهر مبدا')),
                ('to_city', models.CharField(blank=True, max_length=100, verbose_name='شهر مقصد')),
                ('weight_min_kg', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='حداقل وزن (کیلو)')),
                ('weight_max_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='حداکثر وزن (کیلو)')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت')),
                ('extra_per_kg', models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مازاد هر کیلو')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='shipping.shippingmethod', verbose_name='روش ارسال')),
            ],
            options={
                'verbose_name': 'تعرفه ارسال',
                'verbose_name_plural': 'تعرفه\u200cهای ارسال',
                'ordering': ['from_city', 'to_city', 'weight_min_kg'],
            },
        ),
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('provinces', models.JSONField(blank=True, default=list, verbose_name='استان\u200cها')),
                ('cities', models.JSONField(blank=True, default=list, verbose_name='شهرها')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_zones', to='tenants.store', verbose_name='فروشگاه')),
            ],
            options={
                'verbose_name': 'منطقه ارسال',
                'verbose_name_plural': 'مناطق ارسال',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShippingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='تنظیمات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('priority', models.IntegerField(default=0, verbose_name='اولویت')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='shipping.shippingmethod', verbose_name='روش ارسال')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='shipping.shippingzone', verbose_name='منطقه')),
            ],
            options={
                'verbose_name': 'قانون ارسال',
                'verbose_name_plural': 'قوانین ارسال',
                'ordering': ['-priority', 'id'],
            },
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='methods', to='shipping.shippingzone', verbose_name='منطقه'),
        ),
        migrations.AlterUniqueTogether(
            name='shippingmethod',
            unique_together={('store', 'slug')},
        ),
    ]
