# Generated by Django 5.1.15 on 2026-08-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingmethod',
            name='payment_type',
            field=models.CharField(choices=[('prepaid', 'پیش\u200cکرایه'), ('postpaid', 'پس\u200cکرایه')], default='prepaid', max_length=10, verbose_name='نوع پرداخت کرایه'),
        ),
        migrations.AddField(
            model_name='shippingprice',
            name='zone_tier',
            field=models.CharField(blank=True, choices=[('same', 'هم\u200cاستان'), ('adjacent', 'استان مجاور'), ('far', 'دورافتاده')], max_length=10, verbose_name='سطح منطقه'),
        ),
    ]
