# Generated by Django 5.1.15 on 2026-07-09 21:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('tenants', '0002_plugin_storeplugin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('order_number', models.CharField(max_length=32, verbose_name='شماره سفارش')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('waiting_payment', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('preparing', 'در حال آماده\u200cسازی'), ('sent', 'ارسال شده'), ('delivered', 'تحویل شده'), ('canceled', 'لغو شده'), ('refunded', 'بازگشت وجه')], default='waiting_payment', max_length=20, verbose_name='وضعیت')),
                ('address_snapshot', models.JSONField(blank=True, default=dict, verbose_name='آدرس')),
                ('shipping_method', models.CharField(blank=True, max_length=200, verbose_name='روش ارسال')),
                ('shipping_provider', models.CharField(blank=True, max_length=50, verbose_name='ارائه\u200cدهنده ارسال')),
                ('subtotal', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='جمع جزء')),
                ('discount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='تخفیف')),
                ('shipping_cost', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='هزینه ارسال')),
                ('tax', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='مالیات')),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='جمع کل')),
                ('coupon_code', models.CharField(blank=True, max_length=50, verbose_name='کد کوپن')),
                ('customer_note', models.TextField(blank=True, verbose_name='یادداشت مشتری')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='payments.paymenttransaction', verbose_name='پرداخت')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='tenants.store', verbose_name='فروشگاه')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
                'ordering': ['-created_at'],
                'unique_together': {('store', 'order_number')},
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('invoice_number', models.CharField(max_length=32, unique=True, verbose_name='شماره فاکتور')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ صدور')),
                ('pdf_url', models.URLField(blank=True, verbose_name='آدرس PDF')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'فاکتور',
                'verbose_name_plural': 'فاکتورها',
            },
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('waiting_payment', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('preparing', 'در حال آماده\u200cسازی'), ('sent', 'ارسال شده'), ('delivered', 'تحویل شده'), ('canceled', 'لغو شده'), ('refunded', 'بازگشت وجه')], max_length=20, verbose_name='وضعیت')),
                ('note', models.TextField(blank=True, verbose_name='یادداشت')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_history_entries', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'تاریخچه سفارش',
                'verbose_name_plural': 'تاریخچه سفارشات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('product_id', models.IntegerField(verbose_name='شناسه محصول')),
                ('product_name', models.CharField(max_length=300, verbose_name='نام محصول')),
                ('product_slug', models.CharField(blank=True, max_length=300, verbose_name='شناسه محصول')),
                ('variant_id', models.IntegerField(blank=True, null=True, verbose_name='شناسه تنوع')),
                ('variant_label', models.CharField(blank=True, max_length=200, verbose_name='برچسب تنوع')),
                ('sku', models.CharField(blank=True, max_length=100, verbose_name='SKU')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت واحد')),
                ('line_total', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='جمع خط')),
                ('image', models.URLField(blank=True, verbose_name='تصویر')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'آیتم سفارش',
                'verbose_name_plural': 'آیتم\u200cهای سفارش',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('preparing', 'آماده\u200cسازی'), ('shipped', 'ارسال شد'), ('in_transit', 'در مسیر'), ('delivered', 'تحویل شد'), ('returned', 'مرجوعی')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('tracking_code', models.CharField(blank=True, max_length=100, verbose_name='کد رهگیری')),
                ('carrier', models.CharField(blank=True, max_length=100, verbose_name='حامل')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تحویل')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='متادیتا')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'مرسوله',
                'verbose_name_plural': 'مرسوله\u200cها',
            },
        ),
    ]
