# Generated by Django 5.1.15 on 2026-07-09 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gift_card_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='کد کارت هدیه'),
        ),
    ]
