# Generated by Django 5.1.15 on 2026-07-10 08:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_gift_card_code'),
        ('payments', '0001_initial'),
        ('tenants', '0002_plugin_storeplugin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['store', 'status'], name='orders_orde_store_i_610c63_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['store', 'created_at'], name='orders_orde_store_i_8955ea_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['store', 'user'], name='orders_orde_store_i_6a84d2_idx'),
        ),
    ]
