# Generated by Django 5.1.15 on 2026-07-09 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_plugin_storeplugin'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('channel_type', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('push', 'Push'), ('webhook', 'Webhook'), ('telegram', 'Telegram')], max_length=20, verbose_name='نوع')),
                ('provider', models.CharField(max_length=50, verbose_name='ارائه\u200cدهنده')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='تنظیمات')),
                ('is_default', models.BooleanField(default=False, verbose_name='پیش\u200cفرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_channels', to='tenants.store', verbose_name='فروشگاه')),
            ],
            options={
                'verbose_name': 'کانال اعلان',
                'verbose_name_plural': 'کانال\u200cهای اعلان',
                'ordering': ['channel_type', 'provider'],
                'unique_together': {('store', 'channel_type', 'provider')},
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('channel_type', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('push', 'Push'), ('webhook', 'Webhook'), ('telegram', 'Telegram')], max_length=20, verbose_name='نوع')),
                ('provider', models.CharField(max_length=50, verbose_name='ارائه\u200cدهنده')),
                ('recipient', models.CharField(max_length=255, verbose_name='گیرنده')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='موضوع')),
                ('body', models.TextField(verbose_name='متن')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='متادیتا')),
                ('error_message', models.TextField(blank=True, verbose_name='خطا')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='tenants.store', verbose_name='فروشگاه')),
            ],
            options={
                'verbose_name': 'لاگ اعلان',
                'verbose_name_plural': 'لاگ\u200cهای اعلان',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['store', 'channel_type'], name='notificatio_store_i_3a9102_idx'), models.Index(fields=['recipient'], name='notificatio_recipie_8b135e_idx')],
            },
        ),
    ]
