# Generated by Django 5.1.15 on 2026-07-09 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('simple', 'ساده'), ('variable', 'متغیر'), ('digital', 'دیجیتال'), ('subscription', 'اشتراک')], default='simple', max_length=20, verbose_name='نوع'),
        ),
    ]
