# Generated by Django 5.1.15 on 2026-07-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_product_type'),
        ('tenants', '0002_plugin_storeplugin'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['store', 'status'], name='products_pr_store_i_ce0433_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['store', 'created_at'], name='products_pr_store_i_59644a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['store', 'base_price'], name='products_pr_store_i_0a378b_idx'),
        ),
    ]
