# Generated by Django 5.1.15 on 2026-07-31 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_widen_color_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_custom',
            field=models.BooleanField(default=False, help_text='در نوار/خانه تم Pulse به\u200cصورت دستهٔ سفارشی برجسته می\u200cشود.', verbose_name='دسته سفارشی'),
        ),
    ]
