# Generated by Django 5.1.15 on 2026-08-16 16:07

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_category_is_custom'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight_kg',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.5'), max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='وزن (کیلوگرم)'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='وزن (کیلوگرم)'),
        ),
    ]
