# Generated by Django 5.1.15 on 2026-09-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_add_weight_kg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.CharField(max_length=500, verbose_name="تصویر"),
        ),
    ]
