"""Tenant views package."""

from tenants.views.storefront import (
    storefront_404,
    storefront_500,
    storefront_addresses,
    storefront_blog_list,
    storefront_blog_single,
    storefront_cart,
    storefront_category,
    storefront_checkout,
    storefront_cms_page,
    storefront_comments,
    storefront_dashboard,
    storefront_home,
    storefront_invoices,
    storefront_order_detail,
    storefront_order_success,
    storefront_orders,
    storefront_product,
    storefront_profile,
    storefront_profile_edit,
    storefront_search,
    storefront_wishlist,
)

__all__ = [
    "storefront_home",
    "storefront_category",
    "storefront_product",
    "storefront_search",
    "storefront_cart",
    "storefront_checkout",
    "storefront_order_success",
    "storefront_dashboard",
    "storefront_profile",
    "storefront_profile_edit",
    "storefront_wishlist",
    "storefront_orders",
    "storefront_order_detail",
    "storefront_invoices",
    "storefront_comments",
    "storefront_addresses",
    "storefront_blog_list",
    "storefront_blog_single",
    "storefront_cms_page",
    "storefront_404",
    "storefront_500",
]
